package dyliang.seckill.dao;

import dyliang.seckill.domain.ItemDO;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface ItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Aug 06 14:54:33 CST 2020
     */
    int insert(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Aug 06 14:54:33 CST 2020
     */
    int insertSelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Aug 06 14:54:33 CST 2020
     */
    ItemDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Aug 06 14:54:33 CST 2020
     */
    int updateByPrimaryKeySelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Aug 06 14:54:33 CST 2020
     */
    int updateByPrimaryKey(ItemDO record);

    @Select("select * from item")
    List<ItemDO> listItem();

    /**
     * 更新销量
     *
     * @param itemId
     * @param amount
     * @return
     */
    @Update("update item set sales = sales + #{amount} where id = #{itemId}")
    int increaseSales(@Param("itemId") Integer itemId, @Param("amount") Integer amount);
}