package dyliang.seckill.dao;

import dyliang.seckill.domain.ItemStockDO;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ItemStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Aug 06 14:54:33 CST 2020
     */
    int insert(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Aug 06 14:54:33 CST 2020
     */
    int insertSelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Aug 06 14:54:33 CST 2020
     */
    ItemStockDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Aug 06 14:54:33 CST 2020
     */
    int updateByPrimaryKeySelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Aug 06 14:54:33 CST 2020
     */
    int updateByPrimaryKey(ItemStockDO record);

    /**
     * 根据id查询商品
     * @param itemId
     * @return
     */
    @Select("select * from item_stock where item_id = #{id}")
    ItemStockDO selectByItemId(@Param(value = "id")Integer itemId);

    /**
     * 减库存
     * @param itemId
     * @param amount
     * @return
     */
    @Update("update item_stock set stock = stock - #{amount} where item_id = #{itemId} and stock >= #{amount} ")
    int decreaseStock(@Param("itemId") Integer itemId, @Param("amount") Integer amount);
}