package dyliang.seckill.dao;

import dyliang.seckill.domain.PromoDO;
import dyliang.seckill.service.model.PromoModel;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface PromoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Fri Aug 07 15:46:59 CST 2020
     */
    int insert(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Fri Aug 07 15:46:59 CST 2020
     */
    int insertSelective(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Fri Aug 07 15:46:59 CST 2020
     */
    PromoDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Fri Aug 07 15:46:59 CST 2020
     */
    int updateByPrimaryKeySelective(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Fri Aug 07 15:46:59 CST 2020
     */
    int updateByPrimaryKey(PromoDO record);

    /**
     * 根据id查询秒杀商品
     *
     * @param id
     * @return
     */
    @Select("select * from promo where item_id = #{itemId}")
    PromoDO selectByItemId(@Param("itemId") Integer id);
}