package dyliang.seckill.dao;

import dyliang.seckill.domain.SequenceDO;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface SequenceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Fri Aug 07 09:56:19 CST 2020
     */
    int insert(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Fri Aug 07 09:56:19 CST 2020
     */
    int insertSelective(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Fri Aug 07 09:56:19 CST 2020
     */
    SequenceDO selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Fri Aug 07 09:56:19 CST 2020
     */
    int updateByPrimaryKeySelective(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Fri Aug 07 09:56:19 CST 2020
     */
    int updateByPrimaryKey(SequenceDO record);

    /**
     * 获取序列号
     * @param order_info
     * @return
     */
    @Select("select * from sequence_info where name = #{order_info}")
    SequenceDO getSequenceByName(@Param(value = "order_info") String order_info);
}