package dyliang.seckill.dao;

import dyliang.seckill.domain.UserDO;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

@Repository
public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Aug 04 10:13:19 CST 2020
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Aug 04 10:13:19 CST 2020
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Aug 04 10:13:19 CST 2020
     */
    UserDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Aug 04 10:13:19 CST 2020
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Aug 04 10:13:19 CST 2020
     */
    int updateByPrimaryKey(UserDO record);

    /**
     * 根据id查询用户
     *
     * @param id
     * @return
     */
    @Select("select * from user_info u where u.id=#{id}")
    UserDO findUserById(@Param(value = "id") Integer id);

    /**
     * 根据telephone查询用户
     *
     * @param telephone
     * @return
     */
    @Select("select * from user_info where telephone = #{telephone}")
    UserDO selectByTelephone(@Param("telephone") String telephone);
}